### ISSUE TITLE
opencv 4.5.5 dnn 读 onnx模型异常

### ISSUE THREAD

**Issue by opentld** [hpc203/yolov6-opencv-onnxruntime#1]
![image](https://user-images.githubusercontent.com/21096515/175878153-9e7b59e8-616a-4417-b294-a9107e08fb40.png)
opencv 4.5.5 cuda 11.2 的dnn模块，读取onnx模型异常。

**Comment by hpc203** [comment]
> ![image](https://user-images.githubusercontent.com/21096515/175878153-9e7b59e8-616a-4417-b294-a9107e08fb40.png) opencv 4.5.5 cuda 11.2 的dnn模块，读取onnx模型异常。

检查一下onnx模型文件的路径，正确吗

**Comment by hpc203** [comment]
> ![image](https://user-images.githubusercontent.com/21096515/175878153-9e7b59e8-616a-4417-b294-a9107e08fb40.png) opencv 4.5.5 cuda 11.2 的dnn模块，读取onnx模型异常。

如果用cuda加速，建议用onnxruntime做推理引擎做部署

**Comment by opentld** [comment]
> > ![image](https://user-images.githubusercontent.com/21096515/175878153-9e7b59e8-616a-4417-b294-a9107e08fb40.png) opencv 4.5.5 cuda 11.2 的dnn模块，读取onnx模型异常。
> 
> 检查一下onnx模型文件的路径，正确吗

路径肯定是正确的。即便我不设置DNN_BACKEND_CUDA，也是读取异常。。。

**Comment by opentld** [comment]
> > ![image](https://user-images.githubusercontent.com/21096515/175878153-9e7b59e8-616a-4417-b294-a9107e08fb40.png) opencv 4.5.5 cuda 11.2 的dnn模块，读取onnx模型异常。
> 
> 如果用cuda加速，建议用onnxruntime做推理引擎做部署

opencv CUDA 也没问题，读取模型会异常，但似乎不影响使用。
